### ISSUE TITLE
7z SDK Error when creating new library

### ISSUE THREAD

**Issue by tylernguyen** [xthursdayx/yacreaderlibrary-server-docker#1]
executing 

`docker exec YACReaderLibraryServer YACReaderLibraryServer create-library comics /comics`

returns `_7z.c:200: 7z support requires 7z SDK (define HAVE_7Z)`

with my exsting library of cbz files.

System: Unraid 6.9.2 Docker

**Comment by xthursdayx** [comment]
Yeah, unfortunately YACReaderLibraryServer has trouble playing nicely with 7zip, so it uses unarr out of the box instead. However, I'm currently working on trying to bundle p7zip into this Docker image, so hopefully it will work in the future.

**Comment by tylernguyen** [comment]
That would be great, my comics are all in .cbz so it's crucial.

**Comment by xthursdayx** [comment]
I have a number of .cbz comics as well and found that YACReaderLibraryServer still worked with them despite the 7z warning, however, I just pushed an updated version of the Docker image that is bundled with p7zip and seems to be working without any warning. 

I'd suggest removing your existing container and image and deleting the `.yacreaderlibrary` directory that YACReaderLibraryServer created in your root comics directory, then pull the new image and create your library again. Let me know if you run into any issues.

**Comment by Cantello** [comment]
I have deleted all .yacreaderlibrary folders, pulled the latest version of the container (with tag _unarr_ - `xthursdayx/yacreaderlibrary-server-docker:unarr`) and still, after creating a new library I get the error: `! _7z.c:191: 7z support requires 7z SDK (define HAVE_7Z)`.

Any idea what could be wrong?

**Comment by tonicastillo** [comment]
Hi!
I have the same error. Any workaround?
Thanks
