### ISSUE TITLE
[Feature Request] Show post-processed filenames when updating library

### ISSUE THREAD

**Issue by christophedc0** [xthursdayx/yacreaderlibrary-server-docker#20]
## Describe the solution you'd like
I would like to have the filenames in the output when updating the library. 
Currently we only see the number of comics that are added.

Why: Because I receive a summary of the executed task and would like to easily know what has been added (also for manual adding metadata to new comics)

**Comment by xthursdayx** [comment]
This docker container just shows the logs generated by YACReaderLibraryServer, so this issue should be opened in the [YACReader repo](https://github.com/YACReader/yacreader/tree/develop/YACReaderLibraryServer).
