### ISSUE TITLE
[BUG] Missing comma in VOLUME instruction

### ISSUE THREAD

**Issue by itotm** [xthursdayx/yacreaderlibrary-server-docker#30]
I think a comma is missing in the VOLUME directive, so [ and ] are interpreted as volumes

------------------------------

## Expected Behavior
Only 2 volumes detected, /config and /comics

## Current Behavior
"[" and "]" appear as volumes

## Steps to Reproduce
1. launch image with provided command, inside a raspberrypi with portainer.io installed

## Screenshots
Using portainer.io that's what I see
![image](https://user-images.githubusercontent.com/1804363/222929842-2de6e2e8-4df3-402b-9c3e-de39d23eb578.png)

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** arm64 (raspberry pi 4)

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
  --name=yacreaderlibrary-server \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/rome \
  -p 8585:8080 \
  -v /var/docker-volumes/yacreader:/config \
  -v /var/sync/Fumetti:/comics \
  --restart unless-stopped \
  xthursdayx/yacreaderlibrary-server-docker

**Comment by xthursdayx** [comment]
Thanks for pointing this error out @itotm - the latest release fixes this issue.
