### ISSUE TITLE
issue after updating container with init-adduser (v1.4.x)

### ISSUE THREAD

**Issue by christophedc0** [xthursdayx/yacreaderlibrary-server-docker#34]
I have an issue using the latest container images as of v1.4.0.

`docker logs -f YACReaderLibraryServer
s6-rc-compile: fatal: during dependency resolution for service init-adduser: undefined service name init-script-check`

I already tried downgrading the container, but to no success.
The container itself is running on a Synology NAS and shows no errors except the fatal error in the log.

running v1.3.9 has no issues.

**Comment by xthursdayx** [comment]
Thanks for the heads up. This appears to be fixed now. Please re-open this issue and comment if you're still having problems. Cheers.

**Comment by QinshanSun** [comment]
this issue still happens when i use the latest docker image.

**Comment by logicwar** [comment]
This issue still happens with latest version 1.4.6.

**Comment by xthursdayx** [comment]
Apologies, my fix only got pushed through to the `p7zip` image, which I was using for testing, not the `unarr` and `latest` images. The updated images with the fix for all tag versions is currently building and should be up on Docker Hub and the GitHub Container Registry shortly.

**Comment by xthursdayx** [comment]
All tagged images for release [v1.4.7](https://github.com/xthursdayx/yacreaderlibrary-server-docker/releases/tag/v1.4.7) have now been pushed to Docker Hub and the GHCR. Please pull the new image and report back if you're still having any issues. Cheers.

**Comment by logicwar** [comment]
Thank you! The latest version works fine on my side !

**Comment by christophedc0** [comment]
Thanks! It's also fixed on my side! 👍
