### ISSUE TITLE
[BUG] "! rar.c:112: Invalid header checksum @7" error when trying to update the library

### ISSUE THREAD

**Issue by sylvain-lec** [xthursdayx/yacreaderlibrary-server-docker#38]
[BUG] "! rar.c:112: Invalid header checksum @7" error when trying to update the library
------------------------------

## Expected Behavior
I added the library that I specified in the docker-compose file but no comic was showing so I tried to update it via docker exec and I got an error message in the process. It does update the library it seems though.

## Current Behavior
The error message when trying to update the library is: "! rar.c:112: Invalid header checksum @7".

## Steps to Reproduce
1. docker exec YACReaderLibraryServer YACReaderLibraryServer add-library comics /comics
Library added : comics at /comics
2. docker exec YACReaderLibraryServer YACReaderLibraryServer update-library /comics
! rar.c:112: Invalid header checksum @7

## Screenshots
https://imgur.com/AXF20cQ

## Environment
**OS: Synology DSM 7.1.1-42962 Update 6
**CPU architecture: x86_64 (DS920+)

## Command used to create docker container (run/create/compose/screenshot)
services:
yacreaderlibrary-server-docker:
    container_name: YACReaderLibraryServer
    image: xthursdayx/yacreaderlibrary-server-docker
    environment:
      - PUID=1030
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume2/docker/yacreader/config:/config
      - /volume1/Comics:/comics
    ports:
      - 8090:8080
    restart: unless-stopped

## Docker logs
https://imgur.com/aHAoTbV

## Additional information
Thank you for your image and for your help! :)

**Comment by xthursdayx** [comment]
Hi, are you using the p7zip or unarr version of this image?

Based on the error you're getting it appears that this is likely an issue with one of your comics, or more specifically the way that the underlying decompression backend is handling this comic. Unfortunately I am not able to troubleshoot this, so I suggest you post an issue in the main [YACReader repo](https://github.com/YACReader/yacreader/).

**Comment by sylvain-lec** [comment]
Ok, thank you for your feedback!
