### ISSUE TITLE
[BUG] SynologyNAS Library not visible via iPad or Web

### ISSUE THREAD

**Issue by Ghost1299** [xthursdayx/yacreaderlibrary-server-docker#64]
Hello
I created a Library and added Comics with YAC Server on Synology, it creates cover and library.ydb correctly.
Connection via Mac on the same Library also works and the comics are shown on Mac.

Firewall on SynologyNAS is not enabled

------------------------------

## Expected Behavior
Access via iPad oder Web.

## Current Behavior
The Library created is shown but I can't click on it in Web
The Library created is shown but empty on iPad (Looks like you're not reading anything)

## Steps to Reproduce

1.
2.
3.
4.

## Environment
Kernel: "linux" "4.4.302+" Architecture: "x86_64"
OS: "Ubuntu 22.04.2 LTS" Version:  "22.04"

## Docker logs

2024/02/21 14:08:39 | stdout | WARN  2024-02-21T13:08:39.882 QSqlQuery::prepare: database not open
-- | -- | --
2024/02/21 14:08:38 | stdout | WARN  2024-02-21T13:08:38.949 QSqlQuery::prepare: database not open
2024/02/21 14:08:37 | stdout | (Parent is RequestMapper(0x558f2c531a20), parent's thread is QThread(0x558f2c525400), current thread is QThread(0x558f2c534450)
2024/02/21 14:08:37 | stdout | WARN  2024-02-21T13:08:37.262 QObject: Cannot create children for a parent that is in a different thread.
2024/02/21 14:08:20 | stdout | [ls.io-init] done.
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.925 1 more network interfaces detected

2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.924 Running on "192.168.xxx.xxx:8080"
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 YACReaderLibrary starting
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 --------------------------------------------
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 Libraries:  QList("ComicLibrary [1, e4d607f5-77e2-4a5a-81a9-11b30e29b4a7, /comics]")
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 Kernel: "linux" "4.4.302+" Architecture: "x86_64"
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 OS: "Ubuntu 22.04.2 LTS" Version:  "22.04"
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 ---------- System & configuration ----------
2024/02/21 14:08:19 | stdout | INFO  2024-02-21T13:08:19.923 YACReaderLibraryServer attempting to start

## Additional information
Firewall on SynologyNAS is not enabled
I used the recommended "latest" package. 
Hope you can help me

**Comment by Ghost1299** [comment]
You can close this issue, I had to add PUID and PGID in the environment

**Comment by xthursdayx** [comment]
Glad you got it sorted out!
