### ISSUE TITLE
"pzip" branch not found

### ISSUE THREAD

**Issue by benfishbus** [xthursdayx/yacreaderlibrary-server-docker#8]
Using Unraid, via Community Apps, my choice of branches is 'Default', 'latest', or 'pzip'. I chose 'pzip', but creation fails with "manifest for xthursdayx/yacreaderlibrary-server-docker:pzip not found: manifest unknown: manifest unknown." This should probably be 'p7zip', no?

**Comment by xthursdayx** [comment]
Good catch, yes, this is a typo in my UNRAID template. Sorry about that. Updating now and it should be pushed to community apps by later today. Thanks!

**Comment by xthursdayx** [comment]
By the way, you'll have to completely delete your container in order to get the option in Community Apps to choose your branch again. The alternative is to manually change the `Repository` entry on the Docker container settings page to `xthursdayx/yacreaderlibrary-server-docker:p7zip`.

**Comment by benfishbus** [comment]
Thanks! I'll check again later, right now it's still showing up 'pzip'

**Comment by xthursdayx** [comment]
Yeah, it usually takes a bit for Community Apps to update. Like I mentioned, if you'd like you can just pull the p7zip tag directly by updating the repository in your YACReaderLibraryServer container settings page.
